// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nirzrzitstmcrwcjelfy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5pcnpyeml0c3RtY3J3Y2plbGZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ5NjI1MDMsImV4cCI6MjA1MDUzODUwM30.ToBuYz7dm_WxW9vixTTg3WbnxhJ6mAJAj9LdB6b5-Yk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);